In [4]:
#Q1 Convert data table into data frame and display the description

import pandas as pd
file = pd.read_excel("C:\Data\Anmol IDAP Assignment 2\cricket.xlsx")
data = pd.DataFrame(file)
data

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,0,SR Tendulkar (INDIA),1989-2013,664,782,74,34357,248,48.52,50817,67.58,100,164,34,4076,264
1,1,KC Sangakkara (Asia/ICC/SL),2000-2015,594,666,67,28016,319,46.77,42086,66.56,63,153,28,3015,159
2,2,RT Ponting (AUS/ICC),1995-2012,560,668,70,27483,257,45.95,40130,68.48,71,146,39,2781,246
3,3,DPMD Jayawardene (Asia/SL),1997-2015,652,725,62,25957,374,39.15,40100,64.73,54,136,47,2679,170
4,4,JH Kallis (Afr/ICC/SA),1995-2014,519,617,97,25534,224,49.10,45346,56.30,62,149,33,2455,254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,83,DB Vengsarkar (INDIA),1976-1992,245,305,41,10376,166,39.30,15989,50.04,18,58,22,737,41
84,84,ME Trescothick (ENG),2000-2006,202,268,16,10326,219,40.97,15903,64.93,26,52,25,1382,84
85,85,G Gambhir (INDIA),2003-2016,242,283,18,10324,206,38.95,14994,68.85,20,63,20,1188,37
86,86,MD Crowe (NZ),1982-1995,220,271,29,10148,299,41.93,18666,54.36,21,52,12,1037,56
87,87,GW Flower (ZIM),1992-2010,288,337,24,10028,201,32.03,19736,50.81,12,55,34,906,53

In [24]:
#Q2 Display the length of the dataset. Display first 10 records of the dataset. Display last five records of the data set.

k = len(data)
print("Length of dataset", k)

# First 10
data.head(10)
# Last five
data.tail(5)

Length of dataset 88

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,0,SR Tendulkar (INDIA),1989-2013,664,782,74,34357,248,48.52,50817+,67.58,100,164,34,4076,264
1,1,KC Sangakkara (Asia/ICC/SL),2000-2015,594,666,67,28016,319,46.77,42086,66.56,63,153,28,3015,159
2,2,RT Ponting (AUS/ICC),1995-2012,560,668,70,27483,257,45.95,40130,68.48,71,146,39,2781,246
3,3,DPMD Jayawardene (Asia/SL),1997-2015,652,725,62,25957,374,39.15,40100,64.73,54,136,47,2679,170
4,4,JH Kallis (Afr/ICC/SA),1995-2014,519,617,97,25534,224,49.10,45346,56.30,62,149,33,2455,254
5,5,R Dravid (Asia/ICC/INDIA),1996-2012,509,605,72,24208,270,45.41,46564,51.98,48,146,21,2604,66
6,6,V Kohli (INDIA),2008-2022,473,527,77,24130,254,53.62,30483,79.15,71,125,33,2400,258
7,7,BC Lara (ICC/WI),1990-2007,430,521,38,22358,400,46.28,32839,68.08,53,111,33,2601,221
8,8,ST Jayasuriya (Asia/SL),1989-2011,586,651,35,21032,340,34.14,25910,81.17,42,103,53,2486,352
9,9,S Chanderpaul (WI),1994-2015,454,553,94,20988,203,45.72,40150,52.27,41,125,21,2041,126

In [73]:
#Q3 Display the name of the player/players who played maximum match, maximum innings, scored maximum runs.

a = data.iloc[data.Mat.argmax(), 1]
c = data.iloc[data.Inns.argmax(), 1]
b = data.iloc[data.Runs.argmax(), 1]

print("Max Matches;", a)
print("Max Innings;", b)
print("Max Runs;", c)

Max Matches; SR Tendulkar (INDIA)
Max Innings; SR Tendulkar (INDIA)
Max Runs; SR Tendulkar (INDIA)

In [74]:
#Q4 Display the name of the player/players who played minimum match, minimum innings, scored minimum runs( non zero).

am = data.iloc[data.Mat.argmin(), 1]
cm = data.iloc[data.Inns.argmin(), 1]
bm = data.iloc[data.Runs.argmin(), 1]

print("Min Matches;", am)
print("Min Innings;", bm)
print("Min Runs;", cm)

Min Matches; ME Trescothick (ENG)
Min Innings; GW Flower (ZIM)
Min Runs; Babar Azam (PAK)

In [36]:
#Q5 Display total number of players and their average performance, country-wise.

tp = data['Player'].count()
print("Total Players in the dataset;", tp)
data[['Player', 'Ave']]

Total Players in the dataset; 88

                         Player    Ave
0          SR Tendulkar (INDIA)  48.52
1   KC Sangakkara (Asia/ICC/SL)  46.77
2          RT Ponting (AUS/ICC)  45.95
3    DPMD Jayawardene (Asia/SL)  39.15
4        JH Kallis (Afr/ICC/SA)  49.10
..                          ...    ...
83        DB Vengsarkar (INDIA)  39.30
84         ME Trescothick (ENG)  40.97
85            G Gambhir (INDIA)  38.95
86                MD Crowe (NZ)  41.93
87              GW Flower (ZIM)  32.03

[88 rows x 2 columns]

In [32]:
#Q6 Display the playerâ€™s details who scored highest run in least BF.
# Data File has been manually cleaned to remove + in BF attribute
a = 0
b = 0
for index in data.index:
    if (data['Runs'][index] / data['BF'][index]) > b:
        b = (data['Runs'][index] / data['BF'][index])
        a = index
data.loc[a]

Unnamed: 0                              71
Player        Shahid Afridi (Asia/ICC/PAK)
Span                             1996-2018
Mat                                    524
Inns                                   508
NO                                      40
Runs                                 11196
HS                                     156
Ave                                  23.92
BF                                    9809
SR                                  114.14
100                                     11
50                                      51
0                                       44
4s                                    1053
6s                                     476
Name: 71, dtype: object

In [94]:
#Q7 Display the longest span playerâ€™s details. Display the number of players from this country .

data[['Span']]

         Span
0   1989-2013
1   2000-2015
2   1995-2012
3   1997-2015
4   1995-2014
..        ...
83  1976-1992
84  2000-2006
85  2003-2016
86  1982-1995
87  1992-2010

[88 rows x 1 columns]

In [61]:
#Q8 	 Display the details of the players who are currently active.
year = '2022'
for index in data.index:
        if year in data['Span'][index]:
            print(data.iloc[index])

Unnamed: 0                  6
Player        V Kohli (INDIA)
Span                2008-2022
Mat                       473
Inns                      527
NO                         77
Runs                    24130
HS                        254
Ave                     53.62
BF                      30483
SR                      79.15
100                        71
50                        125
0                          33
4s                       2400
6s                        258
Name: 6, dtype: object
Unnamed: 0                  16
Player        LRPL Taylor (NZ)
Span                 2006-2022
Mat                        450
Inns                       510
NO                          84
Runs                     18199
HS                         290
Ave                      42.72
BF                       24847
SR                       73.24
100                         40
50                          93
0                           29
4s                        1766
6s                         273
Name: 16, dtype: object
Unnamed: 0               20
Player        JE Root (ENG)
Span              2012-2022
Mat                     314
Inns                    405
NO                       46
Runs                  17604
HS                      254
Ave                   49.03
BF                    26782
SR                    65.73
100                      44
50                       95
0                        20
4s                     1756
6s                       90
Name: 20, dtype: object
Unnamed: 0                 27
Player        DA Warner (AUS)
Span                2009-2022
Mat                       329
Inns                      407
NO                         25
Runs                    16466
HS                        335
Ave                      43.1
BF                      19074
SR                      86.32
100                        43
50                         84
0                          20
4s                       1833
6s                        256
Name: 27, dtype: object
Unnamed: 0                   28
Player        RG Sharma (INDIA)
Span                  2007-2022
Mat                         420
Inns                        437
NO                           59
Runs                      16250
HS                          264
Ave                       42.98
BF                        18796
SR                        86.45
100                          41
50                           87
0                            28
4s                         1528
6s                          492
Name: 28, dtype: object
Unnamed: 0                    31
Player        KS Williamson (NZ)
Span                   2010-2022
Mat                          324
Inns                         381
NO                            39
Runs                       15889
HS                           251
Ave                        46.45
BF                         23962
SR                          66.3
100                           37
50                            87
0                             18
4s                          1605
6s                           117
Name: 31, dtype: object
Unnamed: 0                             39
Player        Tamim Iqbal (BAN/ICC/World)
Span                            2007-2022
Mat                                   378
Inns                                  439
NO                                     18
Runs                                14914
HS                                    206
Ave                                 35.42
BF                                  20519
SR                                  72.68
100                                    25
50                                     93
0                                      36
4s                                   1728
6s                                    186
Name: 39, dtype: object
Unnamed: 0                 44
Player        AD Mathews (SL)
Span                2008-2022
Mat                       396
Inns                      429
NO                         90
Runs                    13936
HS                        200
Ave                      41.1
BF                      22395
SR                      62.22
100                        16
50                         83
0                          20
4s                       1250
6s                        202
Name: 44, dtype: object
Unnamed: 0                 45
Player        SPD Smith (AUS)
Span                2010-2022
Mat                       285
Inns                      325
NO                         43
Runs                    13887
HS                        239
Ave                     49.24
BF                      21294
SR                      65.21
100                        40
50                         67
0                          13
4s                       1399
6s                        114
Name: 45, dtype: object
Unnamed: 0                       47
Player        Mushfiqur Rahim (BAN)
Span                      2005-2022
Mat                             420
Inns                            465
NO                               66
Runs                          13509
HS                              219
Ave                           33.85
BF                            20977
SR                            64.39
100                              17
50                               73
0                                31
4s                             1284
6s                              153
Name: 47, dtype: object
Unnamed: 0                 48
Player        MJ Guptill (NZ)
Span                2009-2022
Mat                       367
Inns                      402
NO                         27
Runs                    13463
HS                        237
Ave                      35.9
BF                      16565
SR                      81.27
100                        23
50                         76
0                          29
4s                       1385
6s                        383
Name: 48, dtype: object
Unnamed: 0                       52
Player        Shakib Al Hasan (BAN)
Span                      2006-2022
Mat                             388
Inns                            428
NO                               48
Runs                          13205
HS                              217
Ave                           34.75
BF                            16895
SR                            78.15
100                              14
50                               91
0                                23
4s                             1350
6s                              113
Name: 52, dtype: object
Unnamed: 0                72
Player        Q de Kock (SA)
Span               2012-2022
Mat                      261
Inns                     297
NO                        21
Runs                   11165
HS                       178
Ave                    40.45
BF                     12241
SR                      91.2
100                       23
50                        64
0                         15
4s                      1287
6s                       194
Name: 72, dtype: object
Unnamed: 0                  77
Player        Babar Azam (PAK)
Span                 2015-2022
Mat                        226
Inns                       252
NO                          34
Runs                     11017
HS                         196
Ave                      50.53
BF                       13518
SR                       81.49
100                         26
50                          74
0                           14
4s                        1124
6s                         114
Name: 77, dtype: object
Unnamed: 0                      79
Player        EJG Morgan (ENG/IRE)
Span                     2006-2022
Mat                            379
Inns                           361
NO                              56
Runs                         10859
HS                             148
Ave                           35.6
BF                           11530
SR                           94.18
100                             16
50                              64
0                               25
4s                             917
6s                             346
Name: 79, dtype: object
Unnamed: 0                  80
Player        S Dhawan (INDIA)
Span                 2010-2022
Mat                        263
Inns                       282
NO                          14
Runs                     10746
HS                         190
Ave                      40.09
BF                       12119
SR                       88.67
100                         24
50                          54
0                           11
4s                        1331
6s                         140
Name: 80, dtype: object
Unnamed: 0                   82
Player        JM Bairstow (ENG)
Span                  2011-2022
Mat                         250
Inns                        305
NO                           31
Runs                      10453
HS                          167
Ave                       38.14
BF                        13990
SR                        74.71
100                          23
50                           46
0                            28
4s                         1176
6s                          192
Name: 82, dtype: object

In [28]:
# Q9	Display the details of the players having â€˜Mâ€™/ â€™mâ€™ as one of the character in their name.

m = data[data['Player'].str.contains('M|m')]
m

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
3,3,DPMD Jayawardene (Asia/SL),1997-2015,652,725,62,25957,374,39.15,40100,64.73,54,136,47,2679,170
10,10,Inzamam-ul-Haq (Asia/ICC/PAK),1991-2007,499,551,76,20580,329,43.32,32172,63.96,35,129,35,2076,193
13,13,HM Amla (SA/World),2004-2019,349,437,36,18672,311,46.56,28718,65.01,55,88,19,2138,93
19,19,TM Dilshan (SL),1999-2016,497,527,64,17671,193,38.16,21879,80.76,39,83,35,2011,112
21,21,Mohammad Yousuf (Asia/PAK),1998-2010,381,432,52,17300,223,45.52,27357,63.23,39,97,26,1747,142
22,22,MS Dhoni (Asia/INDIA),2004-2019,538,526,142,17266,224,44.96,21834,79.07,16,108,21,1486,359
24,24,GC Smith (Afr/ICC/SA),2002-2014,347,432,25,17236,277,42.34,24943,69.10,37,90,20,2076,94
25,25,MJ Clarke (AUS),2003-2015,394,449,71,17112,329,45.26,26033,65.73,36,86,21,1672,102
26,26,ME Waugh (AUS),1988-2002,372,445,37,16529,173,40.51,26413,62.57,38,97,35,1495,98
28,28,RG Sharma (INDIA),2007-2022,420,437,59,16250,264,42.98,18796,86.45,41,87,28,1528,492
29,29,Javed Miandad (PAK),1975-1996,357,407,62,16213,280,46.99,26178,54.83,31,93,14,1233,92
31,31,KS Williamson (NZ),2010-2022,324,381,39,15889,251,46.45,23962,66.30,37,87,18,1605,117
34,34,M Azharuddin (INDIA),1984-2000,433,455,63,15593,199,39.77,22561,66.92,29,79,14,1342,96
36,36,SP Fleming (ICC/NZ),1994-2008,396,463,31,15319,274,35.46,26979,56.78,17,95,33,1760,89
38,38,ML Hayden (AUS/ICC),1993-2009,273,348,32,15066,380,47.67,22330,67.46,40,69,23,1722,182
39,39,Tamim Iqbal (BAN/ICC/World),2007-2022,378,439,18,14914,206,35.42,20519,72.68,25,93,36,1728,186
40,40,BB McCullum (NZ),2002-2016,432,474,47,14676,302,34.37,17872,82.11,19,76,37,1552,398
43,43,MS Atapattu (SL),1990-2007,360,416,47,14036,249,38.03,24986,56.17,27,76,35,1419,19
44,44,AD Mathews (SL),2008-2022,396,429,90,13936,200,41.10,22395,62.22,16,83,20,1250,202
45,45,SPD Smith (AUS),2010-2022,285,325,43,13887,239,49.24,21294,65.21,40,67,13,1399,114
47,47,Mushfiqur Rahim (BAN),2005-2022,420,465,66,13509,219,33.85,20977,64.39,17,73,31,1284,153
48,48,MJ Guptill (NZ),2009-2022,367,402,27,13463,237,35.90,16565,81.27,23,76,29,1385,383
51,51,SM Gavaskar (INDIA),1971-1987,233,316,30,13214,236,46.20,19150,48.25,35,72,20,1142,47
55,55,Saleem Malik (PAK),1982-1999,386,410,60,12938,237,36.96,20289,61.85,20,76,31,1192,41
57,57,Mohammad Hafeez (PAK),2003-2021,392,429,36,12780,224,32.51,17213,74.24,21,64,34,1370,214
60,60,MEK Hussey (AUS),2004-2013,302,324,71,12398,195,49.00,19208,64.54,22,72,16,1126,144
63,63,Shoaib Malik (ICC/PAK),1999-2021,446,429,79,11867,245,33.90,15292,77.60,12,61,23,1038,199
66,66,A Flower (ZIM),1992-2003,276,320,35,11580,232,40.63,19733,58.68,16,82,18,1075,46
73,73,MN Samuels (WI),2000-2018,345,388,43,11134,260,32.27,17068,65.23,17,64,25,1207,219
74,74,Misbah-ul-Haq (PAK),2001-2017,276,315,64,11132,161,44.35,19386,57.42,10,84,17,898,190
75,75,VVS Laxman (INDIA),1996-2012,220,308,41,11119,281,41.64,21067,52.77,23,66,17,1357,9
76,76,MA Taylor (AUS),1989-1999,217,296,14,11039,334,39.14,24048,45.90,20,68,9,1000,16
77,77,Babar Azam (PAK),2015-2022,226,252,34,11017,196,50.53,13518,81.49,26,74,14,1124,114
79,79,EJG Morgan (ENG/IRE),2006-2022,379,361,56,10859,148,35.60,11530,94.18,16,64,25,917,346
81,81,MV Boucher (Afr/ICC/SA),1997-2012,467,448,87,10469,147,29.00,16808,62.28,6,61,33,1034,105
82,82,JM Bairstow (ENG),2011-2022,250,305,31,10453,167,38.14,13990,74.71,23,46,28,1176,192
84,84,ME Trescothick (ENG),2000-2006,202,268,16,10326,219,40.97,15903,64.93,26,52,25,1382,84
85,85,G Gambhir (INDIA),2003-2016,242,283,18,10324,206,38.95,14994,68.85,20,63,20,1188,37
86,86,MD Crowe (NZ),1982-1995,220,271,29,10148,299,41.93,18666,54.36,21,52,12,1037,56
87,87,GW Flower (ZIM),1992-2010,288,337,24,10028,201,32.03,19736,50.81,12,55,34,906,53

In [48]:
# Q10	Display details of players with : maximum & minimum 100,4s and 6s

print('Max 100s by: ', data.set_index('Player')[100].idxmax())
print('Min 100s by: ', data.set_index('Player')[100].idxmin())

print('Max 4s by: ', data.set_index('Player')['4s'].idxmax())
print('Min 4s by: ', data.set_index('Player')['4s'].idxmin())

print('Max 6s by: ', data.set_index('Player')['6s'].idxmax())
print('Min 6s by: ', data.set_index('Player')['6s'].idxmin())

Max 100s by:  SR Tendulkar (INDIA)
Min 100s by:  MV Boucher (Afr/ICC/SA)
Max 4s by:  SR Tendulkar (INDIA)
Min 4s by:  DB Vengsarkar (INDIA)
Max 6s by:  CH Gayle (ICC/WI)
Min 6s by:  VVS Laxman (INDIA)

'SR Tendulkar (INDIA)'